services:
  ubuntu-desktop:
    build: .
    container_name: ubuntu
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      - VNC_PW=password
    restart: always
    shm_size: '512m'If 
